version: "3.9"

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: novago-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: novago
      POSTGRES_PASSWORD: novago
      POSTGRES_DB: novago
    ports:
      - "5432:5432"
    volumes:
      - novago_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: novago-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - novago_redis_data:/data

volumes:
  novago_pg_data:
  novago_redis_data:
