-- Fare audit trail + dispatch reputation and escalation.
--
-- Every column here is additive and either nullable or defaulted, so this is
-- safe to apply to a live table with existing rows and needs no backfill:
-- historical trips simply have no quote/escalation history, which is honest
-- — we did not record it at the time.
--
-- Hand-written rather than generated by `prisma migrate diff`, because that
-- needs a shadow database and there is no local Postgres on the machine this
-- was authored on. Column names and types mirror the schema exactly; if this
-- ever drifts, `prisma migrate status` against the deployed database is the
-- check that catches it.

-- AlterTable: fare integrity.
-- finalFare is deliberately redundant with `fare`. `fare` means "the number";
-- finalFare means "the number, stamped at completion, to compare against
-- acceptedFare". The invariant finalFare = acceptedFare is then one SQL query
-- across every trip, rather than something inferred from application logs.
ALTER TABLE "trips" ADD COLUMN     "quotedFare" DECIMAL(10,2),
ADD COLUMN     "acceptedFare" DECIMAL(10,2),
ADD COLUMN     "finalFare" DECIMAL(10,2),
ADD COLUMN     "fareVersion" TEXT,
ADD COLUMN     "quotedAt" TIMESTAMP(3),
ADD COLUMN     "fareDriftedAt" TIMESTAMP(3);

-- AlterTable: dispatch escalation timestamps.
ALTER TABLE "trips" ADD COLUMN     "offerCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "noDriverFoundAt" TIMESTAMP(3),
ADD COLUMN     "opsAlertedAt" TIMESTAMP(3),
ADD COLUMN     "opsEscalatedAt" TIMESTAMP(3);

-- AlterTable: driver reputation counters the matcher scores on.
ALTER TABLE "driver_profiles" ADD COLUMN     "offersSent" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "offersAccepted" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "offersDeclined" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "tripsCancelled" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "lastOfferAt" TIMESTAMP(3),
ADD COLUMN     "lastCompletedAt" TIMESTAMP(3);

-- The ops desk lists jobs that matching has not placed, newest first, and
-- polls it continuously while the desk is open. Without this it is a
-- sequential scan of every trip ever taken on every poll.
CREATE INDEX "trips_opsAlertedAt_idx" ON "trips"("opsAlertedAt");
CREATE INDEX "trips_noDriverFoundAt_idx" ON "trips"("noDriverFoundAt");
